Usuarios\UsuariosBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        username: 
            expose: true
        password:
            expose: false
        salt:
            expose: false
        roles:
            expose: false
        email:
            expose: false
