admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

AdminBundle_calificacion:
        resource: "@AdminBundle/Resources/config/routing/calificacion.yml"
        prefix:   /calificacion
