calificacion:
    path:     /
    defaults: { _controller: "AdminBundle:Calificacion:index" }

calificacion_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Calificacion:show" }

calificacion_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Calificacion:new" }

calificacion_create:
    path:     /create
    defaults: { _controller: "AdminBundle:Calificacion:create" }
    requirements: { _method: post }

calificacion_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Calificacion:edit" }

calificacion_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:Calificacion:update" }
    requirements: { _method: post|put }

calificacion_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Calificacion:delete" }
    requirements: { _method: post|delete }
