comentario:
    path:     /
    defaults: { _controller: "AdminBundle:Comentario:index" }

comentario_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Comentario:show" }

comentario_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Comentario:new" }

comentario_create:
    path:     /create
    defaults: { _controller: "AdminBundle:Comentario:create" }
    requirements: { _method: post }

comentario_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Comentario:edit" }

comentario_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:Comentario:update" }
    requirements: { _method: post|put }

comentario_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Comentario:delete" }
    requirements: { _method: post|delete }
