experiencia:
    path:     /
    defaults: { _controller: "AdminBundle:Experiencias:index" }

experiencia_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Experiencias:show" }

experiencia_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Experiencias:new" }

experiencia_create:
    path:     /create
    defaults: { _controller: "AdminBundle:Experiencias:create" }
    requirements: { _method: post }

experiencia_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Experiencias:edit" }

experiencia_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:Experiencias:update" }
    requirements: { _method: post|put }

experiencia_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Experiencias:delete" }
    requirements: { _method: post|delete }
