perfil:
    path:     /
    defaults: { _controller: "AdminBundle:Perfil:index" }

perfil_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Perfil:show" }

perfil_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Perfil:new" }

perfil_create:
    path:     /create
    defaults: { _controller: "AdminBundle:Perfil:create" }
    requirements: { _method: post }

perfil_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Perfil:edit" }

perfil_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:Perfil:update" }
    requirements: { _method: post|put }

perfil_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Perfil:delete" }
    requirements: { _method: post|delete }
